name: Next

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'next.config.js'
      - 'tsconfig.json'
      - 'yarn.lock'
      - '.github/workflows/build-next.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'next.config.js'
      - 'tsconfig.json'
      - 'yarn.lock'
      - '.github/workflows/build-next.yml'

jobs:
  build-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '22'
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn export
