name: Next

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'next.config.js'
      - 'tsconfig.json'
      - 'yarn.lock'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'next.config.js'
      - 'tsconfig.json'
      - 'yarn.lock'

jobs:
  build-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn export
